[package]
name        = "shallowred"
description = "ShallowRed — moteur d'échecs UCI"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
authors.workspace    = true

[lints]
workspace = true

[lib]
name = "shallowred"
path = "src/lib.rs"

[[bin]]
name = "shallowred"
path = "src/main.rs"

[dependencies]
cozy-chess = "0.3.4"
